Remove implicit assumption that Pynab is installed in /home/pi.

diff --git a/bin/check_pynab_syntax b/bin/check_pynab_syntax
--- a/bin/check_pynab_syntax
+++ b/bin/check_pynab_syntax
@@ -4,8 +4,10 @@
 set_defaults() {
 	SELF=$(basename "${0}")
 	# Pynab defaults
-	USER=pi
-	PYNAB=${HOME}/pynab
+	systemd_dir="/lib/systemd/system"
+	nabd_service=${systemd_dir}/nabd.service
+	PYNAB=$(sed -nE -e 's|WorkingDirectory=(.+)|\1|p' ${nabd_service} 2>/dev/null)
+
 	BLACK_OPTS="-l 79"
 	PYCODESTYLE_OPTS="--ignore=E121,E123,E126,E226,E24,E704,W503,W504,E203"
 	FLAKE8_OPTS="--extend-ignore=E203,E501"
@@ -27,15 +29,16 @@ set_defaults() {
 	fi
 }
 # ------------------------------
-check_user() {
-	if [ "$(id -un)" != "${USER}" ]; then
-		/bin/echo "${RED}${SELF} must be run as user ${USER}.${STD}"
-		exit 1
+check_pynab() {
+	if [ ! -d "${PYNAB}" ]; then
+		/bin/echo "${RED}Cannot locate Pynab repository!${STD}"
+		exit 42
 	fi
 
-	if [ ! -d "${PYNAB}" ]; then
-		/bin/echo "${RED}Pynab repository '${PYNAB}' not found!${STD}"
-		exit 42
+        owner=`stat -c '%U' ${PYNAB}`
+	if [ "$(id -un)" != "${owner}" ]; then
+		/bin/echo "${RED}${SELF} must be run as user ${owner}.${STD}"
+		exit 1
 	fi
 }
 # ------------------------------
@@ -143,7 +146,7 @@ run_isort() {
 }
 # ------------------------------
 set_defaults
-check_user
+check_pynab
 get_options $*
 run_black ${BLACK}
 run_pycodestyle ${PYCODESTYLE}
diff --git a/bin/migrate_pynab_models b/bin/migrate_pynab_models
--- a/bin/migrate_pynab_models
+++ b/bin/migrate_pynab_models
@@ -4,8 +4,10 @@
 set_defaults() {
 	SELF=$(basename "${0}")
 	# Pynab defaults
-	USER=pi
-	PYNAB=${HOME}/pynab
+	systemd_dir="/lib/systemd/system"
+	nabd_service=${systemd_dir}/nabd.service
+	PYNAB=$(sed -nE -e 's|WorkingDirectory=(.+)|\1|p' ${nabd_service} 2>/dev/null)
+
 	MAKE=""
 	MIGRATE=""
 
@@ -20,15 +22,16 @@ set_defaults() {
 	fi
 }
 # ------------------------------
-check_user() {
-	if [ "$(id -un)" != "${USER}" ]; then
-		/bin/echo "${RED}${SELF} must be run as user ${USER}.${STD}"
-		exit 1
+check_pynab() {
+	if [ ! -d "${PYNAB}" ]; then
+		/bin/echo "${RED}Cannot locate Pynab repository!${STD}"
+		exit 42
 	fi
 
-	if [ ! -d "${PYNAB}" ]; then
-		/bin/echo "${RED}Pynab repository '${PYNAB}' not found!${STD}"
-		exit 42
+        owner=`stat -c '%U' ${PYNAB}`
+	if [ "$(id -un)" != "${owner}" ]; then
+		/bin/echo "${RED}${SELF} must be run as user ${owner}.${STD}"
+		exit 1
 	fi
 }
 # ------------------------------
@@ -91,7 +94,7 @@ migrate() {
 }
 # ------------------------------
 set_defaults
-check_user
+check_pynab
 get_options $*
 make_migrations ${MAKE}
 migrate ${MIGRATE}
diff --git a/bin/rebuild_pynab_drivers b/bin/rebuild_pynab_drivers
--- a/bin/rebuild_pynab_drivers
+++ b/bin/rebuild_pynab_drivers
@@ -4,8 +4,10 @@
 set_defaults() {
 	SELF=$(basename "${0}")
 	# Pynab defaults
-	USER=pi
-	PYNAB=${HOME}/pynab
+	systemd_dir="/lib/systemd/system"
+	nabd_service=${systemd_dir}/nabd.service
+	PYNAB=$(sed -nE -e 's|WorkingDirectory=(.+)|\1|p' ${nabd_service} 2>/dev/null)
+
 	REBUILD=""
 
 	if [ -t 1 ]
@@ -19,15 +21,18 @@ set_defaults() {
 	fi
 }
 # ------------------------------
-check_user() {
-	if [ "$(id -un)" != "${USER}" ]; then
-		/bin/echo "${RED}${SELF} must be run as user ${USER}.${STD}"
-		exit 1
+check_pynab() {
+	if [ ! -d "${PYNAB}" ]; then
+		/bin/echo "${RED}Cannot locate Pynab repository!${STD}"
+		exit 42
+	else
+		ROOT=$(dirname ${PYNAB})
 	fi
 
-	if [ ! -d "${PYNAB}" ]; then
-		/bin/echo "${RED}Pynab repository '${PYNAB}' not found!${STD}"
-		exit 42
+        owner=`stat -c '%U' ${PYNAB}`
+	if [ "$(id -un)" != "${owner}" ]; then
+		/bin/echo "${RED}${SELF} must be run as user ${owner}.${STD}"
+		exit 1
 	fi
 }
 # ------------------------------
@@ -69,7 +74,7 @@ build_driver() {
 	driver=$1
 	driver_type=$2
 	/bin/echo -e "\n${BLUE}${driver_type} driver...${STD}"
-	cd ${HOME}
+	cd ${ROOT}
 	if [ ! -d "${driver}" ]; then
 		cmd="/usr/bin/git clone https://github.com/pguyot/${driver}" ; /bin/echo "${BOLD}${cmd}${STD}"
 		eval $cmd
@@ -92,14 +97,14 @@ build_driver() {
 }
 # ------------------------------
 reboot_after_build() {
-	cd ${HOME}
+	cd ${ROOT}
 	/bin/echo -e "\n${RED}Rebooting...${STD}"
 	cmd="/usr/bin/sudo /bin/systemctl reboot" ; /bin/echo "${BOLD}${cmd}${STD}"
 	eval $cmd
 }
 # ------------------------------
 set_defaults
-check_user
+check_pynab
 get_options $*
 check_rebuild ${REBUILD}
 
diff --git a/bin/update_pynab_messages b/bin/update_pynab_messages
--- a/bin/update_pynab_messages
+++ b/bin/update_pynab_messages
@@ -4,8 +4,10 @@
 set_defaults() {
 	SELF=$(basename "${0}")
 	# Pynab defaults
-	USER=pi
-	PYNAB=${HOME}/pynab
+	systemd_dir="/lib/systemd/system"
+	nabd_service=${systemd_dir}/nabd.service
+	PYNAB=$(sed -nE -e 's|WorkingDirectory=(.+)|\1|p' ${nabd_service} 2>/dev/null)
+
 	MODULE_LIST='nab?*d nabweb'
 	LOCALES="-l en_US -l en_GB -l fr_FR -l it_IT -l es_ES -l pt_BR -l de_DE -l ja_jP"
 	MAKE=""
@@ -22,15 +24,16 @@ set_defaults() {
 	fi
 }
 # ------------------------------
-check_user() {
-	if [ "$(id -un)" != "${USER}" ]; then
-		/bin/echo "${RED}${SELF} must be run as user ${USER}.${STD}"
-		exit 1
+check_pynab() {
+	if [ ! -d "${PYNAB}" ]; then
+		/bin/echo "${RED}Cannot locate Pynab repository!${STD}"
+		exit 42
 	fi
 
-	if [ ! -d "${PYNAB}" ]; then
-		/bin/echo "${RED}Pynab repository '${PYNAB}' not found!${STD}"
-		exit 42
+        owner=`stat -c '%U' ${PYNAB}`
+	if [ "$(id -un)" != "${owner}" ]; then
+		/bin/echo "${RED}${SELF} must be run as user ${owner}.${STD}"
+		exit 1
 	fi
 }
 # ------------------------------
@@ -111,7 +114,7 @@ compile_messages() {
 }
 # ------------------------------
 set_defaults
-check_user
+check_pynab
 get_options $*
 make_messages ${MAKE}
 compile_messages ${COMPILE}
