Cleanup error messages.

diff --git a/bin/pynab b/bin/pynab
--- a/bin/pynab
+++ b/bin/pynab
@@ -35,7 +35,7 @@ set_defaults() {
 }
 # ------------------------------
 usage() {
-	[ -n "${1}" ] && echo "${SELF}: illegal option ${1}"
+	[ -n "${1}" ] && echo "Illegal option ${1}" >&2
 	echo "Usage: ${SELF} [-status | -start | -stop | -restart | -local | -public | -log [NUM]]"
 	echo "\tno option :\tshow status of Pynab services"
 	echo "\t    -help :\tthis usage help"
@@ -68,9 +68,8 @@ get_options() {
 	    -log)
 		case ${ARG2} in
 		    *[!0-9]*)
-			echo "Invalid NUM value for '-log': ${BOLD}${ARG2}${STD}!"
-			usage
-			exit 42 ;;
+			echo "Invalid NUM value for '-log': ${BOLD}'${ARG2}'${STD}!" >&2
+			usage; exit 42 ;;
 		    '')
 			ARG=10 ;;
 		    *)
diff --git a/bin/tagtagtag-sound b/bin/tagtagtag-sound
--- a/bin/tagtagtag-sound
+++ b/bin/tagtagtag-sound
@@ -59,7 +59,7 @@ tagtagtag_sound() {
 
 		case ${SPEAKER_LOW} in
 		    *[!0-9]*)
-			echo "Invalid minimum value: ${BOLD}${SPEAKER_LOW}${STD}!"
+			echo "Invalid minimum value: ${BOLD}'${SPEAKER_LOW}'${STD}!" >&2
 			SPEAKER_LOW=${CUR_SPEAKER_LOW} ;;
 		    '')
 			SPEAKER_LOW=${CUR_SPEAKER_LOW} ;;
@@ -69,7 +69,7 @@ tagtagtag_sound() {
 
 		case ${SPEAKER_HIGH} in
 		    *[!0-9]*)
-			echo "Invalid maximum value: ${BOLD}${SPEAKER_HIGH}${STD}!"
+			echo "Invalid maximum value: ${BOLD}'${SPEAKER_HIGH}'${STD}!" >&2
 			SPEAKER_HIGH=${CUR_SPEAKER_HIGH} ;;
 		    '')
 			SPEAKER_HIGH=${CUR_SPEAKER_HIGH} ;;
